# Generated by Django 3.0.3 on 2020-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrList',
            fields=[
                ('irno', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rfc', models.CharField(max_length=1)),
            ],
        ),
    ]
